/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include<stdlib.h>
#include<stdio.h>
#include<string.h>
/* Header for class com_example_mirsmeng_ndk01_MainActivity */

#ifndef _Included_com_example_mirsmeng_ndk01_MainActivity
#define _Included_com_example_mirsmeng_ndk01_MainActivity
#ifdef __cplusplus
extern "C" {
#endif


//c 中的一个工具类 java字符串转c字符串方法
char*   Jstring2CStr(JNIEnv*   env,   jstring   jstr)
{
 char*   rtn   =   NULL;
 jclass   clsstring   =   (*env)->FindClass(env,"java/lang/String");
 jstring   strencode   =   (*env)->NewStringUTF(env,"GB2312");
 jmethodID   mid   =   (*env)->GetMethodID(env,clsstring,   "getBytes",   "(Ljava/lang/String;)[B");
 jbyteArray   barr=   (jbyteArray)(*env)->CallObjectMethod(env,jstr,mid,strencode);
 jsize   alen   =   (*env)->GetArrayLength(env,barr);
 jbyte*   ba   =   (*env)->GetByteArrayElements(env,barr,JNI_FALSE);
 if(alen   >   0)
 {
  rtn   =   (char*)malloc(alen+1);         //new   char[alen+1];
  memcpy(rtn,ba,alen);
  rtn[alen]=0;
 }
 (*env)->ReleaseByteArrayElements(env,barr,ba,0);
 return rtn;
}

//获取c中的字符串
JNIEXPORT jstring JNICALL Java_com_example_mirsmeng_ndk01_MainActivity_getJniStr(JNIEnv * env,jobject obj){

    char* str = "我是c中的字符串";

    return (**env).NewStringUTF(env,str);

}

//把字符串中的每个字符做 +1操作  char* 代表c中的字符串类型
JNIEXPORT jstring JNICALL Java_com_example_mirsmeng_ndk01_MainActivity_getStrAdd
  (JNIEnv * env, jobject obj, jstring str, jint len){

    char* cStr = Jstring2CStr(env,str);

    int i;
    for(i=0;i<len;i++){
        *(cStr+i) = *(cStr+i)+1;
    }
    return (**env).NewStringUTF(env,cStr);
}

//产生一个0-99之间的随机数
JNIEXPORT jint JNICALL Java_com_example_mirsmeng_ndk01_MainActivity_getRandom
  (JNIEnv * env, jobject obj){

    return rand() % 100;
}

#ifdef __cplusplus
}
#endif
#endif
